"""Refresh the website's game list from the checked-in catalog."""

import json
import re
from pathlib import Path


WEB = Path(__file__).resolve().parent
CATALOG = WEB.parents[1] / "catalog" / "catalog.json"
FEATURED = [
    "steam-1086940", "steam-250900", "steam-646570", "steam-108600",
    "steam-105600", "steam-268500", "steam-588650", "steam-632360",
    "steam-212680", "steam-281990", "steam-394360", "steam-219740",
    "steam-311690", "steam-881100", "steam-379430", "steam-203770",
    "steam-590380", "steam-594570", "steam-418530", "steam-333640",
]


def value_text(info):
    match = re.search(r"\*\*SaveScummer value:\*\*\s*(.*?)(?:\n\n|$)", info, re.S)
    if not match:
        raise ValueError("Missing SaveScummer value")
    text = re.sub(r"\*\*(.*?)\*\*", r"\1", match.group(1))
    return " ".join(text.split())


def image_path(game_id, suffix):
    if not game_id.startswith("steam-"):
        return None
    path = f"games/{game_id[6:]}-{suffix}"
    return path if (WEB / "dist" / path).is_file() else None


catalog = json.loads(CATALOG.read_text(encoding="utf-8"))["games"]
by_id = {game["id"]: game for game in catalog}
if len(by_id) != len(catalog) or any(game_id not in by_id for game_id in FEATURED):
    raise ValueError("Featured game IDs do not match the catalog")

ordered = [by_id[game_id] for game_id in FEATURED]
ordered += sorted(
    (game for game in catalog if game["id"] not in FEATURED),
    key=lambda game: game["name"].casefold(),
)
data = [
    {
        "name": game["name"],
        "value": value_text(game["info"]),
        "hero": image_path(game["id"], "hero.jpg"),
        "logo": image_path(game["id"], "logo.png"),
    }
    for game in ordered
]
(WEB / "dist" / "games-data.js").write_text(
    "// Generated by apps/web/update-games.py from catalog/catalog.json.\n"
    + "window.savescummerGames = "
    + json.dumps(data, ensure_ascii=False, indent=2)
    + ";\n",
    encoding="utf-8",
)
print(f"Updated {len(data)} games ({len(FEATURED)} featured).")
