[package]
name = "savescummer-platform"
version.workspace = true
edition.workspace = true

[dependencies]
savescummer-core.workspace = true
savescummer-monitor.workspace = true
savescummer-scanner.workspace = true
dunce = "1"

[target.'cfg(windows)'.dependencies]
windows-sys = { workspace = true, features = ["Win32_Media_Audio", "Win32_UI_Input_KeyboardAndMouse", "Win32_System_Console"] }

[dev-dependencies]
tempfile.workspace = true
