[package]
name = "savescummer-monitor"
version.workspace = true
edition.workspace = true
publish = false

[dependencies]

[target.'cfg(unix)'.dependencies]
libc.workspace = true

[target.'cfg(target_os = "macos")'.dependencies]
objc2.workspace = true
objc2-foundation.workspace = true
objc2-app-kit.workspace = true
block2.workspace = true

[target.'cfg(windows)'.dependencies]
windows-sys.workspace = true
