[package]
name = "xtask"
version.workspace = true
edition.workspace = true
publish = false

[dependencies]
savescummer-catalog-build.workspace = true
anyhow.workspace = true
clap.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
hex.workspace = true
uuid.workspace = true
chrono.workspace = true
ureq = "3"
toml = "1"
toml_edit = "0.25"
sysinfo = { version = "0.39", default-features = false, features = ["system"] }

[target.'cfg(windows)'.dependencies]
windows-sys.workspace = true
