[package]
name = "savescummer-snapshots"
version.workspace = true
edition.workspace = true

[dependencies]
savescummer-core.workspace = true
blake3 = "1"

[target.'cfg(windows)'.dependencies]
windows-sys.workspace = true

[target.'cfg(unix)'.dependencies]
libc = "0.2"

[dev-dependencies]
tempfile.workspace = true
