//! The APP PACKAGE (PLAN-BUILD.md APP PACKAGE): the assembled, runnable app
//! under `build/<mode>/package/`, and exactly what the release file wraps.
//!
//! Every package contains:
//!
//! - the three executables (two until the UI exists) and what they need
//! - the frontend's license texts
//! - `THIRD-PARTY-LICENSES.html`, generated by cargo-about
//! - `.savescummer-package.json`, which marks it as generated output
//! - `SHA256SUMS.txt`
//!
//! A package is assembled in a fresh `.staging-<uuid>` sibling and swapped
//! into place only when complete, so a failed build never damages the
//! existing one.

use std::collections::{BTreeMap, BTreeSet};
use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;

use anyhow::{Context, bail};
use serde_json::{Value, json};
use sha2::{Digest, Sha256};

use crate::frontend::{self, Ui};
use crate::paths::{self, Mode};
use crate::{cmd, naming, pins, platform, procs};

pub const MANIFEST: &str = ".savescummer-package.json";
pub const SUMS: &str = "SHA256SUMS.txt";
pub const THIRD_PARTY: &str = "THIRD-PARTY-LICENSES.html";

/// What goes into a package.
pub struct Inputs<'a> {
    pub mode: Mode,
    pub version: &'a str,
    /// Cargo's host and CLI executables (renamed when packaged). Read by the
    /// platform packaging, which only Windows has yet.
    #[cfg_attr(not(windows), allow(dead_code))]
    pub host: PathBuf,
    #[cfg_attr(not(windows), allow(dead_code))]
    pub cli: PathBuf,
    pub ui: Option<&'a Ui>,
}

/// Where a platform module put things inside a package.
pub struct Layout {
    /// Licenses, notices, manifest and checksums go here.
    pub resources: PathBuf,
    /// Files that must exist, relative to the package root.
    pub required: Vec<PathBuf>,
}

/// The finished package folder (`build/<mode>/package/<name>`).
pub fn location(mode: Mode) -> PathBuf {
    mode.package_parent().join(platform::package_name())
}

pub fn assemble(inputs: &Inputs) -> anyhow::Result<PathBuf> {
    let parent = inputs.mode.package_parent();
    fs::create_dir_all(&parent).with_context(|| format!("creating {}", parent.display()))?;
    remove_leftovers(&parent);

    let staging = parent.join(format!(".staging-{}", uuid::Uuid::new_v4().simple()));
    let guard = Cleanup(Some(staging.clone()));
    fs::create_dir_all(&staging)?;
    println!("assembling the {} package", inputs.mode.name());

    let layout = platform::fill_package(&staging, inputs)?;
    fs::create_dir_all(&layout.resources)?;
    if inputs.ui.is_some() {
        let licenses = frontend::licenses();
        if !has_files(&licenses) {
            bail!("the UI's license texts are missing from {}", paths::show(&licenses));
        }
        copy_dir(&licenses, &layout.resources.join("licenses"))?;
    }
    third_party_licenses(&layout.resources.join(THIRD_PARTY))?;
    write_manifest(&layout.resources.join(MANIFEST), inputs)?;

    let missing: Vec<String> =
        layout.required.iter().filter(|p| !staging.join(p).exists()).map(|p| p.display().to_string()).collect();
    if !missing.is_empty() {
        bail!("the package is missing {}", missing.join(", "));
    }
    write_sums(&staging, &layout.resources.join(SUMS))?;

    let target = location(inputs.mode);
    swap(&staging, &target)?;
    std::mem::forget(guard);
    println!("package ready: {}", paths::show(&target));
    Ok(target)
}

/// Replaces `target` with `staging`, after stopping anything running from it.
fn swap(staging: &Path, target: &Path) -> anyhow::Result<()> {
    procs::stop_under(target)?;
    let old = target.with_file_name(format!(".old-{}", uuid::Uuid::new_v4().simple()));
    if target.exists() {
        fs::rename(target, &old).with_context(|| format!("moving the old package {} aside", target.display()))?;
    }
    if let Err(e) = fs::rename(staging, target) {
        if old.exists() {
            let _ = fs::rename(&old, target);
        }
        return Err(e).with_context(|| format!("moving the new package into {}", target.display()));
    }
    if old.exists() {
        let _ = fs::remove_dir_all(&old);
    }
    Ok(())
}

/// Removes staging and old folders a crashed build left behind.
fn remove_leftovers(parent: &Path) {
    let Ok(entries) = fs::read_dir(parent) else { return };
    for entry in entries.flatten() {
        let name = entry.file_name().to_string_lossy().into_owned();
        if name.starts_with(".staging-") || name.starts_with(".old-") {
            let _ = fs::remove_dir_all(entry.path());
        }
    }
}

/// Removes an unfinished staging folder when assembly fails.
struct Cleanup(Option<PathBuf>);

impl Drop for Cleanup {
    fn drop(&mut self) {
        if let Some(dir) = self.0.take() {
            let _ = fs::remove_dir_all(dir);
        }
    }
}

fn write_manifest(path: &Path, inputs: &Inputs) -> anyhow::Result<()> {
    let manifest = json!({
        "generated": "This folder is build output of `cargo xtask`; it is replaced on every build.",
        "mode": inputs.mode.name(),
        "version": inputs.version,
        "platform": platform::PLATFORM.stem(),
        "qt": inputs.ui.map(|_| frontend::version()),
        "configuration": {
            "rust": match inputs.mode { Mode::Dev => "dev", Mode::Release => "release" },
            "ui": inputs.ui.map(|_| frontend::configuration(inputs.mode)),
        },
        "created": chrono::Utc::now().to_rfc3339_opts(chrono::SecondsFormat::Secs, true),
    });
    fs::write(path, serde_json::to_string_pretty(&manifest)? + "\n")
        .with_context(|| format!("writing {}", path.display()))
}

/// `<sha256>  <path>` for every file in the package, sorted, `/`-separated.
fn write_sums(root: &Path, out: &Path) -> anyhow::Result<()> {
    let mut lines = Vec::new();
    for file in files(root)? {
        let relative = file.strip_prefix(root).expect("walked from root").to_string_lossy().replace('\\', "/");
        lines.push(format!("{}  {relative}", sha256_file(&file)?));
    }
    lines.sort_by(|a, b| a[66..].cmp(&b[66..]));
    fs::write(out, lines.join("\n") + "\n").with_context(|| format!("writing {}", out.display()))
}

pub fn sha256_file(path: &Path) -> anyhow::Result<String> {
    let mut file = fs::File::open(path).with_context(|| format!("reading {}", path.display()))?;
    let mut hasher = Sha256::new();
    std::io::copy(&mut file, &mut hasher).with_context(|| format!("reading {}", path.display()))?;
    Ok(hex::encode(hasher.finalize()))
}

/// Every file under `dir`, recursively.
pub fn files(dir: &Path) -> anyhow::Result<Vec<PathBuf>> {
    let mut out = Vec::new();
    let mut stack = vec![dir.to_path_buf()];
    while let Some(dir) = stack.pop() {
        for entry in fs::read_dir(&dir).with_context(|| format!("reading {}", dir.display()))? {
            let entry = entry?;
            if entry.file_type()?.is_dir() {
                stack.push(entry.path());
            } else {
                out.push(entry.path());
            }
        }
    }
    Ok(out)
}

fn has_files(dir: &Path) -> bool {
    files(dir).map(|f| !f.is_empty()).unwrap_or(false)
}

pub fn copy_file(from: &Path, to: &Path) -> anyhow::Result<()> {
    if let Some(parent) = to.parent() {
        fs::create_dir_all(parent)?;
    }
    fs::copy(from, to).with_context(|| format!("copying {} to {}", from.display(), to.display()))?;
    Ok(())
}

/// Copies the contents of `from` into `to`, merging with what's there.
pub fn copy_dir(from: &Path, to: &Path) -> anyhow::Result<()> {
    for file in files(from)? {
        copy_file(&file, &to.join(file.strip_prefix(from).expect("walked from root")))?;
    }
    Ok(())
}

/// Generates `THIRD-PARTY-LICENSES.html` for the crates the host and CLI
/// link. A crate under a license `about.toml` doesn't accept fails the build.
fn third_party_licenses(out: &Path) -> anyhow::Result<()> {
    let tool = cmd::tool(
        &paths::tools().join("cargo-about").join("bin").join(naming::exe("cargo-about")),
        &format!("cargo-about {}", pins::CARGO_ABOUT_VERSION),
        "cargo-about",
    )?;
    let root = paths::root();
    let scratch = paths::scratch();
    fs::create_dir_all(&scratch)?;
    let mut reports = Vec::new();
    for app in ["host", "cli"] {
        let json = scratch.join(format!("licenses-{app}.json"));
        let mut command = Command::new(&tool);
        command
            .current_dir(&root)
            .arg("generate")
            .args(["--format", "json", "--fail", "--locked", "--target", platform::RUST_TARGET])
            .arg("-c")
            .arg(root.join("about.toml"))
            .arg("-m")
            .arg(root.join("apps").join(app).join("Cargo.toml"))
            .arg("-o")
            .arg(&json);
        cmd::run(&mut command)
            .context("third-party licenses: a dependency's license isn't in about.toml, or couldn't be identified")?;
        let text = fs::read_to_string(&json)?;
        reports.push(serde_json::from_str::<Value>(&text).context("reading cargo-about's report")?);
    }
    fs::write(out, render_licenses(&reports)).with_context(|| format!("writing {}", out.display()))
}

/// One page listing each distinct license text once, with the crates under it.
fn render_licenses(reports: &[Value]) -> String {
    // (license name, text) → crates using that exact text
    let mut licenses: BTreeMap<(String, String), BTreeSet<String>> = BTreeMap::new();
    for report in reports {
        for license in report["licenses"].as_array().into_iter().flatten() {
            let name = license["name"].as_str().unwrap_or("Unknown").to_string();
            let text = license["text"].as_str().unwrap_or_default().to_string();
            let crates = licenses.entry((name, text)).or_default();
            for used in license["used_by"].as_array().into_iter().flatten() {
                let krate = &used["crate"];
                crates.insert(format!(
                    "{} {}",
                    krate["name"].as_str().unwrap_or("?"),
                    krate["version"].as_str().unwrap_or("?")
                ));
            }
        }
    }
    let mut html = String::from(
        "<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n<meta charset=\"utf-8\">\n<title>SaveScummer third-party licenses</title>\n\
         <style>body{font-family:sans-serif;max-width:60em;margin:2em auto;padding:0 1em}pre{white-space:pre-wrap;background:#f4f4f4;padding:1em}</style>\n\
         </head>\n<body>\n<h1>Third-party licenses</h1>\n<p>SaveScummer's host and command-line programs include these Rust crates.</p>\n",
    );
    for ((name, text), crates) in &licenses {
        html.push_str(&format!(
            "<h2>{}</h2>\n<p>Used by: {}</p>\n<pre>{}</pre>\n",
            escape(name),
            escape(&crates.iter().cloned().collect::<Vec<_>>().join(", ")),
            escape(text)
        ));
    }
    html.push_str("</body>\n</html>\n");
    html
}

fn escape(text: &str) -> String {
    text.replace('&', "&amp;").replace('<', "&lt;").replace('>', "&gt;")
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn license_page_merges_reports() {
        let report = |krate: &str| json!({ "licenses": [{ "name": "MIT License", "text": "<text>", "used_by": [{ "crate": { "name": krate, "version": "1.0.0" } }] }] });
        let html = render_licenses(&[report("a"), report("b")]);
        assert_eq!(html.matches("<h2>MIT License</h2>").count(), 1);
        assert!(html.contains("Used by: a 1.0.0, b 1.0.0"));
        assert!(html.contains("&lt;text&gt;"));
    }
}
