[package]
name = "savescummer-cli"
version.workspace = true
edition.workspace = true

[dependencies]
savescummer-core.workspace = true
savescummer-ipc.workspace = true
savescummer-platform.workspace = true
serde_json.workspace = true
tokio.workspace = true
clap.workspace = true
anyhow.workspace = true

[build-dependencies]
winresource = "0.1.31"

[package.metadata.winresource]
ProductName = "SaveScummer"
FileDescription = "SaveScummer Command-Line Client"
OriginalFilename = "SaveScummer.CLI.exe"
InternalName = "SaveScummer.CLI"
CompanyName = "SaveScummer contributors"
LegalCopyright = "SaveScummer contributors"
