[package]
name = "savescummer-cli"
version.workspace = true
edition.workspace = true
publish = false

[lib]
path = "src/lib.rs"

[[bin]]
name = "savescummer-cli"
path = "src/main.rs"

[dependencies]
savescummer-ipc.workspace = true
savescummer-platform.workspace = true
serde.workspace = true
serde_json.workspace = true
clap.workspace = true

[build-dependencies]
winresource.workspace = true
